services:
  api:
    extends:
      file: docker-compose.internal.yml
      service: api
    networks:
      - message-network
      - webserver
    labels:
      - traefik.enable=true
      - traefik.docker.network=webserver
      - traefik.http.routers.whatsappproject.rule=Host(`whatsapp.vierkant-ai.eu`)
      - traefik.http.routers.whatsappproject.entrypoints=websecure
      - traefik.http.routers.whatsappproject.tls=true
      - traefik.http.routers.whatsappproject.tls.certresolver=le
      - traefik.http.services.whatsappproject.loadbalancer.server.port=3000
      - traefik.http.services.whatsappproject.loadbalancer.server.scheme=http
  database:
    extends:
      file: docker-compose.internal.yml
      service: database

networks:
  message-network:
    driver: bridge
  webserver:
    external: true

volumes:
  postgres_data:
    driver: local
  files:
